[tool.poetry]
name = "scripts"
version = "0.1.0"
description = ""
authors = ["Jack Grigg <jack@electriccoin.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.scripts]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
